baseurl = "http://kikudai.com/"
languageCode = "ja"
title = "kikudai's blog"
disqusShortname = "kikudai"
theme = "angels-ladder"

[Params]
subtitle = "人生何が起こるか分からない。"
facebook = "https://facebook.com/kikudai"
twitter = "https://twitter.com/dai__ki"
github = "https://github.com/kikudai"
showsRSS = true
profile = "/img/profile.png"
copyright = "Written by Daichi Kikuchi"
analytics = "UA-18994391-5"
shareThis = "19955610-5f55-40c1-b5a2-2d4423574d3b"