baseurl = "/"
languageCode = "ja"
title = "kikudai blog"
disqusShortname = "kikudai"
theme = "hugo-ink"
hasCJKLanguage = true
paginate = 5
copyright = "Written by Daichi Kikuchi"

[taxonomies]
  tag = "tags"

[markup.goldmark.renderer]
  unsafe = true
